AWSTemplateFormatVersion: "2010-09-09"
Description: Create IAM Role
Resources:
  # IAM Role (SSM)
  SSMIAMRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName:
        Fn::Sub: "launch-template-ssm-role"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  SSMInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    DeletionPolicy: Retain
    Properties:
      InstanceProfileName:
        Fn::Sub: "launch-template-ssm-role"
      Path: "/"
      Roles:
        - Ref: SSMIAMRole
        
Outputs:
  SSMInstanceProfile:
    Value: !GetAtt SSMInstanceProfile.Arn
    Export:
      Name: SSMInstanceProfile