AWSTemplateFormatVersion: "2010-09-09"
Description: Create Security Group
Resources:
# Security Group
  EC2SecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "launch-template-sg"
      GroupDescription: "launch-template-sg"
      VpcId: { "Fn::ImportValue": !Sub "VPC" }
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort : 80
          ToPort : 80
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: "Name"
          Value: launch-template-sg
        
Outputs:
  EC2SecurityGroup1:
    Value: !Ref EC2SecurityGroup1
    Export:
      Name: EC2SecurityGroup1